swagger: '2.0'
info:
  title: Category API
  version: 1.0.0
  description: API for category management

tags:
  - name: Category
    description: Category management

paths:
  /api/Category/List:
    get:
      tags:
        - Category
      summary: Get all entities
      description: Get all entities
      responses:
        '200':
          description: Get all entities
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
        '404':
          description: Not found
        '401':
          description: Unauthorized

  /api/Category/Get/{id}:
    get:
      tags:
        - Category
      summary: Get a Category
      description: Get a Category
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Category id
      responses:
        '200':
          description: Get a Category
        '404':
          description: Not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/Category/Create:
    post:
      tags:
        - Category
      summary: Create a Category
      description: Create a Category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/SaveCategory'
      responses:
        '201':
          description: Create a Category
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/Category/Update/{id}:
    put:
      tags:
        - Category
      summary: Update a Category
      description: Update a Category
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Category id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/SaveCategory'
      responses:
        '200':
          description: Update a Category
        '404':
          description: Not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/Category/Delete/{id}:
    delete:
      tags:
        - Category
      summary: Delete a Category
      description: Delete a Category
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Category id
      responses:
        '200':
          description: Delete a Category
        '404':
          description: Not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

definitions:
  SaveCategory:
    type: object
    properties:
      name:
        type: string
        description: Category name
    example:
      name: Category name

  Category:
    type: object
    properties:
      id:
        type: string
        description: Category id
      name:
        type: string
        description: Category name
    example:
      name: Category name
